// 01-Dictionary-app-react/src/App.jsx
import { useState } from "react"
import Result from "./components/Result"
import Alert from "./components/Alert"

function App() {
  const [word, setWord] = useState("")
  const [errror, setError] = useState("")
  const [data, setData] = useState([])
  
  const handleSubmit = async (e) => {
    e.preventDefault();
    if(word === "") {
      setError("El campo de busqueda no puede estar vacío")

      setTimeout(() => {
        setError("")
      }, 2000)
      return
    }

    try {
      const response = await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${word}`)
      const result = await response.json()
      setData(result)
    } catch (error) {
      console.log(error);
    }
  }
  return (
    <>
    <div className="container">
      {
        errror && <Alert>{errror}</Alert>
      }

    <form onSubmit={handleSubmit} className="form">
      <input onChange={e => setWord(e.target.value)} type="text" className="search" placeholder="serene" />
      <button className="search-button">Search</button>
    </form>
    {
      data && data.map(dictionary => (
        <Result
          key={dictionary.word}
          dictionary={dictionary}
        />
      ))
    }
  </div>
    </>
  )
}

export default App

// 01-Dictionary-app-vue/src/App.vue
<script setup>
import Result from "./components/Result.vue"
import { ref } from "vue"
import Alert from "./components/Alert.vue";

const word = ref("")
const data = ref({})
const error = ref("")

const fetchData = async () => {
  if(word.value === "") {
    error.value = "El campo no puede estar vacío"
    return;
  }

  try {
    const resposne = await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${word.value}`)
    const result = await resposne.json()
    data.value = result
    
  } catch (error) {
    console.log(error);
  }
}

</script>

<template>
  <div class="container">
    <Alert v-if="error">
      {{ error }}
    </Alert>
    <form @submit.prevent="fetchData" class="form">
      <input v-model="word" type="text" class="search" placeholder="serene" />
      <button class="search-button">Search</button>
    </form>
    <Result v-for="dictionary in data" :dictionary="dictionary" />
  </div>
</template>
