// 02-crud-todoList-react/src/App.jsx
import { useState, useReducer } from "react"
import Alert from "./components/Alert"
import { todoReducer } from "./reducers/todo-reducer"
import Todo from "./components/Todo"

function App() {


  const initialState = {
    todos: [],
    activeId: ''
  }

  const [state, dispatch] = useReducer(todoReducer, initialState)

  const [error, setError] = useState("")
  const [newTodo, setNewTodo] = useState({
    title: "",
    id: null
  })

  const handleSubmit = (e) => {
    e.preventDefault()
    if(newTodo.title === "") {
      setError("El campo no puede ir vacío")
      setTimeout(() => {
        setError("")
      }, 2000);
      return
    }

    dispatch({type: 'add-todo', payload: {...newTodo, id:Date.now()}})
    setNewTodo({
      title: "",
      id: null
    })
  }

  const deleteTodo = (id) => {
    dispatch({type: "delete-todo", payload: id})
  }

  const updateId = (todo) => {
    setNewTodo(todo)
    dispatch({type: "set-id", payload: todo.id})
  }

  return (
    <>
      {error && <Alert>{error}</Alert>}
      <div className="container">
        <h2>Todo list</h2>
        <form onSubmit={handleSubmit} className="input-container form">
            <input value={newTodo.title} onChange={e => setNewTodo({...newTodo, title: e.target.value})} className="input-text" type="text" placeholder="Añadir un item" />
            <button>Añadir item</button>
        </form>
        <div className="content-todos">
          {
            state.todos.map(todo => (
              <Todo todo={todo} key={todo.id} deleteTodo={deleteTodo} updateId={updateId} />
            ))
          }
        </div>
    </div>
    </>
  )
}

export default App

// 02-crud-todoList-vue/src/App.vue
<script setup>
import { ref } from 'vue';
import useTodos from './composables/useTodos';
import Alert from './components/Alert.vue';
import Item from './components/Item.vue';

const { todo, todos, createTodo, deleteTodo, updateTodo } = useTodos()

const error = ref("")

const handleSubmit = () => {
  if (todo.title === "") {
    error.value = "El campo no puede ir vacío"

    setTimeout(() => {
      error.value = ""
    }, 3000)
    return
  }

  if (todo.id) {
    const findIndexTodo = todos.value.findIndex(item => item.id === todo.id)
    todos.value[findIndexTodo] = { ...todo }
  } else {
    createTodo()
  }

  Object.assign(todo, { id: null, title: ""})
}

</script>

<template>
  <Alert v-if="error">{{ error }}</Alert>
  <div class="container">
    <h2>Todo list</h2>
    <form @submit.prevent="handleSubmit" class="input-container form">
      <input v-model="todo.title" class="input-text" type="text" placeholder="Añadir un item">
      <button>{{ todo.id ? "Editar item" : "Añadir item" }}</button>
    </form>
    <div class="content-todos">
      <Item v-for="item in todos" :item="item" :key="item.id" :deleteTodo="deleteTodo" :updateTodo="updateTodo" />
    </div>
  </div>
</template>
